// Test data
module.exports = [
    {
        name: 'CN Tower',
        value: 1700000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Toronto, Ontario',
    },
    {
        name: 'Parliament Hill',
        value: 1125000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Ottawa, Ontario',
    },
    {
        name: 'Calgary Tower',
        value: 450000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Calgary, Alberta',
    },
    {
        name: 'Vancouver Convention Centre',
        value: 1100000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Vancouver, British Columbia',
    },
    {
        name: 'Rideau Canal',
        value: 600000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Ottawa, Ontario',
    },
    {
        name: 'Halifax Citadel',
        value: 500000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Halifax, Nova Scotia',
    },
    {
        name: 'St. Lawrence Market',
        value: 750000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Toronto, Ontario',
    },
    {
        name: 'Mountain Equipment Co-op',
        value: 650000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Vancouver, British Columbia',
    },
    {
        name: 'Palais des Congres',
        value: 900000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Montreal, Quebec',
    },
    {
        name: 'Banff Gondola',
        value: 550000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Banff, Alberta',
    },
    {
        name: 'Château Frontenac',
        value: 1200000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Quebec City, Quebec',
    },
    {
        name: 'Saskatoon Western Development Museum',
        value: 600000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Saskatoon, Saskatchewan',
    },
    {
        name: 'Jasper SkyTram',
        value: 450000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Jasper, Alberta',
    },
    {
        name: 'Victoria Parliament Buildings',
        value: 900000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Victoria, British Columbia',
    },
    {
        name: 'Capilano Suspension Bridge',
        value: 700000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'North Vancouver, British Columbia',
    },
    {
        name: 'Grosse Ile and the Irish Memorial National Historic Site',
        value: 500000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Grosse Ile, Quebec',
    },
    {
        name: 'Niagara Falls',
        value: 850000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Niagara Falls, Ontario',
    },
    {
        name: 'Mount Royal Park',
        value: 650000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Montreal, Quebec',
    },
    {
        name: 'Butchart Gardens',
        value: 750000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Brentwood Bay, British Columbia',
    },
    {
        name: 'The Forks National Historic Site',
        value: 550000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Winnipeg, Manitoba',
    },
    {
        name: 'Signal Hill',
        value: 650000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'St. Johns, Newfoundland and Labrador',
    },
    {
        name: 'Old Quebec',
        value: 850000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Quebec City, Quebec',
    },
    {
        name: 'The Royal Tyrrell Museum',
        value: 750000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Drumheller, Alberta',
    },
    {
        name: 'Haida Gwaii',
        value: 950000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Haida Gwaii, British Columbia',
    },
    {
        name: 'Sainte-Anne-de-Beaupré',
        value: 650000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Sainte-Anne-de-Beaupré, Quebec',
    },
    {
        name: 'L Anse aux Meadows',
        value: 850000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'L Anse aux Meadows, Newfoundland and Labrador',
    },
    {
        name: 'The Bay of Fundy',
        value: 750000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Bay of Fundy, New Brunswick',
    },
    {
        name: 'Gros Morne National Park',
        value: 950000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Gros Morne, Newfoundland and Labrador',
    },
    {
        name: 'The Canadian Museum of History',
        value: 850000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Gatineau, Quebec',
    },
    {
        name: 'The Canadian Museum of Human Rights',
        value: 950000000,
        description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        location: 'Winnipeg, Manitoba',
    }
];
 
